version: "3"

tasks:
  setup-dev:
    cmds:
      - node --version
      - npm install -g npm@latest
      - npm install -g @commitlint/cli @commitlint/config-conventional
      - go install github.com/go-swagger/go-swagger/cmd/swagger@latest
      - go install github.com/swaggo/swag/cmd/swag@latestswag
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.60.3



  cover:
    cmds:
      - go test -coverprofile=${TMPDIR}/c.out ./...
      - go tool cover -html="${TMPDIR}/c.out"
